pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // bilibili ijkplayer was published to the now-defunct JCenter; the
        // aliyun public mirror still serves its arm64-v8a AAR.
        maven { url = uri("https://maven.aliyun.com/repository/public") }
        // JitPack for libraries distributed only via GitHub releases.
        maven { url = uri("https://jitpack.io") }
    }
}

rootProject.name = "hello-digitalis"
include(":hello-vulkan")
include(":hello-jni")
include(":hello-jniCallback")
include(":exceptions")
include(":bitmap-plasma")
include(":hello-gl2")
include(":gles3jni")
include(":native-activity")
include(":native-audio")
include(":native-codec")
include(":native-midi")
include(":sensor-graph")
include(":camera-basic")
include(":camera-texture-view")
include(":teapots-classic")
include(":teapots-more")
include(":teapots-textured")
include(":endless-tunnel")
include(":sanitizers")
include(":unit-test")
include(":vectorization")
include(":orderfile")
include(":hello-gles1")
include(":hello-gles3")
include(":hello-msaa")
include(":hello-ijkplayer")
include(":hello-opencv")
include(":hello-sqlcipher")
include(":hello-conscrypt")
include(":hello-graphics-path")
include(":hello-gif")
include(":hello-zxing")
include(":hello-quickjs")
include(":hello-sqlite-bundled")
include(":hello-tflite")
include(":hello-litert-llm")
include(":hello-libpag")
include(":hello-zstd")
include(":hello-libvlc")
include(":hello-lynx")
include(":hello-mmkv")
include(":hello-aaudio")
include(":hello-binder-ndk")
include(":hello-webview-functor")
include(":hello-nnapi")
include(":hello-fp-vector")
include(":hello-neon")
include(":hello-sha-crypto")
include(":hello-ld-interleave")
include(":hello-superpack-regress")
include(":hello-barriers")
include(":hello-bf16")
include(":hello-bti")
include(":hello-complex")
include(":hello-dotprod")
include(":hello-fp16")
include(":hello-jscvt")
include(":hello-libc-libm")
include(":hello-lrcpc")
include(":hello-lse")
include(":hello-ldxp")
include(":hello-cntvct")
include(":hello-sigaction")
include(":hello-aes")
include(":hello-cronet")
include(":hello-pac-ret")
include(":hello-widemul")
include(":screenshot-test-lib")
include(":status-test-lib")
include(":hello-reactnative")
include(":hello-ink")
include(":hello-appsearch")
include(":hello-libsignal")
include(":hello-fresco")
include(":hello-objectbox")
include(":hello-pdfium")
include(":hello-tracing-perfetto")
include(":renderscript-toolkit")
include(":hello-renderscript-toolkit")
include(":hello-pytorch")
include(":hello-gpuimage")
include(":hello-camera-core")
include(":hello-tesseract")
include(":hello-oboe")
include(":hello-ffmpeg-kit")
include(":hello-ncnn")
include(":hello-onnxruntime")
include(":hello-jna")
include(":hello-libsodium")
include(":hello-j2v8")
include(":hello-couchbase")
include(":hello-avif")
include(":hello-themis")
include(":hello-wcdb")
include(":hello-vosk")
include(":hello-mediapipe")
include(":hello-rive")
include(":hello-argon2")
include(":hello-webrtc")
include(":hello-duktape")
include(":hello-wireguard")
include(":hello-javet")
include(":hello-maplibre")
// (ML Kit barcode was dropped — its pipeline requires Google Play Services,
// absent on the AOSP Digitalis emulator — and replaced by hello-rive, a native
// vector-animation runtime; native barcode is already covered by hello-zxing,
// which decodes via the native C++ zxing-cpp runtime.)
include(":hello-fbjni")
include(":hello-libtorrent4j")
include(":hello-javacpp")
include(":hello-snappy")
include(":hello-libyuv")
include(":hello-secp256k1")
include(":hello-filament")
include(":hello-gltfio")
include(":hello-openblas")
include(":hello-fftw")
include(":hello-gsl")
include(":hello-leptonica")
include(":hello-box2d")
// hello-filament-render is present on disk but intentionally NOT registered — a
// documented known gap. Root-caused: Filament's Android platform layer (shared by
// BOTH the OpenGL and Vulkan backends) dlopen()s libgui.so when it creates the
// on-screen SwapChain; Digitalis does not provide libgui.so as a guest library
// (it is a large C++/binder/SurfaceFlinger system lib), so the dlopen returns
// NULL and the guest then executes a host address -> berberis_HandleNoExec SIGSEGV
// (the same missing-libgui.so class seen elsewhere, not a translator instruction
// bug). Filament's native engine itself works (see the registered hello-filament
// headless smoke). Becomes a live screenshot sample once a guest libgui.so is
// provided.
// include(":hello-filament-render")
