pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        // bilibili ijkplayer was published to the now-defunct JCenter; the
        // aliyun public mirror still serves its arm64-v8a AAR.
        maven { url = uri("https://maven.aliyun.com/repository/public") }
        // JitPack for libraries distributed only via GitHub releases.
        maven { url = uri("https://jitpack.io") }
        // Artifex hosts the MuPDF (fitz) Android AAR here; it is not on Maven Central.
        maven { url = uri("https://maven.ghostscript.com") }
    }
}

rootProject.name = "hello-digitalis"
include(":hello-vulkan")
include(":hello-jni")
include(":hello-jniCallback")
include(":exceptions")
include(":bitmap-plasma")
include(":hello-gl2")
include(":gles3jni")
include(":native-activity")
include(":native-audio")
include(":native-codec")
include(":native-midi")
include(":sensor-graph")
include(":camera-basic")
include(":camera-texture-view")
include(":teapots-classic")
include(":teapots-more")
include(":teapots-textured")
include(":endless-tunnel")
include(":sanitizers")
include(":unit-test")
include(":vectorization")
include(":orderfile")
include(":hello-gles1")
include(":hello-gles3")
include(":hello-msaa")
include(":hello-ijkplayer")
include(":hello-opencv")
include(":hello-sqlcipher")
include(":hello-conscrypt")
include(":hello-graphics-path")
include(":hello-gif")
include(":hello-zxing")
include(":hello-quickjs")
include(":hello-sqlite-bundled")
include(":hello-tflite")
include(":hello-litert-llm")
include(":hello-libpag")
include(":hello-zstd")
include(":hello-libvlc")
include(":hello-lynx")
include(":hello-mmkv")
include(":hello-aaudio")
include(":hello-binder-ndk")
include(":hello-jnihelp")
include(":hello-webview-functor")
include(":hello-nnapi")
include(":hello-fp-vector")
include(":hello-neon")
include(":hello-glyphblit")
include(":hello-sha-crypto")
include(":hello-ld-interleave")
include(":hello-superpack-regress")
include(":hello-barriers")
include(":hello-vktexture")
include(":hello-bf16")
include(":hello-bti")
include(":hello-complex")
include(":hello-dotprod")
include(":hello-fp16")
include(":hello-jscvt")
include(":hello-libc-libm")
include(":hello-lrcpc")
include(":hello-lse")
include(":hello-ldxp")
include(":hello-cntvct")
include(":hello-sigaction")
include(":hello-seccomp")
include(":hello-aes")
include(":hello-eglext")
include(":hello-fcsel")
include(":hello-fp16arith")
include(":hello-i8mm-bf16")
include(":hello-lsepair")
include(":hello-neonmisc")
include(":hello-fcma")
include(":hello-lseatomics")
include(":hello-fdsweep")
include(":hello-cronet")
include(":hello-pac-ret")
include(":hello-widemul")
include(":screenshot-test-lib")
include(":status-test-lib")
include(":bench-lib")
include(":hello-reactnative")
include(":hello-ink")
include(":hello-appsearch")
include(":hello-libsignal")
include(":hello-fresco")
include(":hello-objectbox")
include(":hello-pdfium")
include(":hello-tracing-perfetto")
include(":renderscript-toolkit")
include(":hello-renderscript-toolkit")
include(":hello-pytorch")
include(":hello-gpuimage")
include(":hello-camera-core")
include(":hello-tesseract")
include(":hello-oboe")
include(":hello-ffmpeg-kit")
include(":hello-ncnn")
include(":hello-onnxruntime")
include(":hello-jna")
include(":hello-libsodium")
include(":hello-j2v8")
include(":hello-couchbase")
include(":hello-avif")
include(":hello-themis")
include(":hello-wcdb")
include(":hello-vosk")
include(":hello-mediapipe")
include(":hello-rive")
include(":hello-argon2")
include(":hello-webrtc")
include(":hello-duktape")
include(":hello-wireguard")
include(":hello-javet")
include(":hello-maplibre")
// (ML Kit barcode was dropped — its pipeline requires Google Play Services,
// absent on the AOSP Digitalis emulator — and replaced by hello-rive, a native
// vector-animation runtime; native barcode is already covered by hello-zxing,
// which decodes via the native C++ zxing-cpp runtime.)
include(":hello-fbjni")
include(":hello-libtorrent4j")
include(":hello-javacpp")
include(":hello-snappy")
include(":hello-libyuv")
include(":hello-secp256k1")
include(":hello-filament")
include(":hello-gltfio")
include(":hello-openblas")
include(":hello-fftw")
include(":hello-gsl")
include(":hello-leptonica")
include(":hello-box2d")
include(":hello-filament-render")
include(":hello-lua")
include(":hello-mupdf")
include(":hello-sentry-ndk")
include(":hello-bullet")
include(":hello-libwebp")
include(":hello-libarchive")
include(":hello-opus")
include(":hello-leveldb")
include(":hello-pcre2")
include(":hello-libxml2")
include(":hello-blowfish")
include(":hello-bcrypt")
