plugins {
    id 'com.android.library'
}

android {
    namespace 'com.example.hellodigitalis.screenshottest'
    compileSdk 35
    defaultConfig {
        minSdk 24
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    api 'androidx.test:runner:1.5.2'
    api 'androidx.test.ext:junit:1.1.5'
    api 'androidx.test.uiautomator:uiautomator:2.3.0'
}
