/*
 * Copyright (C) 2026 utzcoz
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// A minimal fbjni HybridClass: a Java object (DigitalisCompute) backed by a C++
// peer allocated through makeCxxInstance(). This exercises fbjni's *hybrid
// dispatch* machinery under ARM64->x86_64 translation — native-peer
// construction, the mHybridData pointer round-trip, and native-method thunks
// generated by makeNativeMethod — which is exactly the path React Native's
// bridge, PyTorch Mobile and Yoga drive at runtime, not merely the library
// load. All arithmetic is integer so a translator miscompile changes the
// computed result rather than passing silently.

#include <fbjni/fbjni.h>

#include <cstdint>

using namespace facebook::jni;

namespace {

struct DigitalisCompute : public HybridClass<DigitalisCompute> {
  static constexpr auto kJavaDescriptor = "Lcom/example/hellofbjni/DigitalisCompute;";

  explicit DigitalisCompute(jint seed) : seed_(seed) {}

  // Called from the Java constructor; allocates the C++ peer and hands its
  // opaque handle back through fbjni to be stored in the Java mHybridData field.
  static local_ref<jhybriddata> initHybrid(alias_ref<jclass>, jint seed) {
    return makeCxxInstance(seed);
  }

  // Native compute dispatched into the C++ peer via fbjni's registered thunk.
  // seed_ is set in the constructor, so a correct result also proves the peer
  // retained its constructor state across the JNI boundary under translation.
  jint combine(jint a, jint b) { return a * a - b * b + a * b + seed_; }

  static void registerNatives() {
    registerHybrid({
        makeNativeMethod("initHybrid", DigitalisCompute::initHybrid),
        makeNativeMethod("combine", DigitalisCompute::combine),
    });
  }

 private:
  friend HybridBase;
  jint seed_;
};

}  // namespace

JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void* /*reserved*/) {
  return initialize(vm, [] { DigitalisCompute::registerNatives(); });
}
